### ISSUE TITLE
Minor issue with pop-ups

### ISSUE THREAD

**Issue by otherguy1971** [cborrow/InsurgencySandstormRcon#2]
First, this is a great little utility. Nice job!!! It does exactly what is needed and has a clean and easy to use UI. I look forward to using this to monitor our Insurgency Sandstorm servers and hope that new features and functionality continue to be developed and added to this application. 

I noticed a minor issue that you may already be aware of, but I thought I would mention it in case you weren't. When I run the application and begin setting up servers, after a minute or so of inactivity, small pop-up windows begin appearing and continue to appear periodically. 

These windows must be manually dismissed by clicking on the 'OK' button before I can continue with set-up. Once the servers are configured, the pop-ups no longer appear, so it appears to be an issue only during initial set-up. See attached screen shot. 

Thanks again for creating this utility!

![pop-ups](https://user-images.githubusercontent.com/74274941/98747894-7c201800-2386-11eb-9ef1-e3e385d2d8c5.jpg)

**Comment by cborrow** [comment]
Thanks for using the software and especially for submitting a ticket. From what you said this looks to be in relation to the program attempting to auto-update a servers info.

May I ask if this happened after starting the program, or after closing a server?

I will make changes necessary for the auto-update feature and get a new version released.

**Comment by otherguy1971** [comment]
Hi, Cory.

Thanks for the quick response. It looks like you may have already addressed the issue, but to answer your question, this issue would occur just after starting the program, but before either: 1) completing the set-up up a server the first time, or 2) selecting an existing server to view, once I had it configured. 

Depending on how long it would take me to finish entering all of the connection details when creating a new server entry, the pop-ups would end up appearing a couple of times before I could complete the set-up process. However, once I finished setting up a server and actually selected a server to view, the pop-ups would obviously disappear. 

Again, thanks for your work on this. It's a great little utility that comes in handy for viewing our servers when I'm not in game. We have 4-6 servers configured at the moment, so it makes managing these easy while I am either in just one of them, or perhaps not actively playing.

**Comment by cborrow** [comment]
Great, thanks for the info. I figured that what it was but just wanted to be sure there wasn't a different issue I couldn't replicate. I don't have any servers I run right now but likely will have another in the future so I'll get to use this more.

But, if you do have any suggestions on things you would like to see, maybe things you end up needed to do on the server a lot, or things you need to send custom commands from the console, please let me know as there is a good chance it is something I can get implemented on here.
