### ISSUE TITLE
Editing existing servers creates new duplicate entries in server list

### ISSUE THREAD

**Issue by otherguy1971** [cborrow/InsurgencySandstormRcon#4]
I am running v1.0.4 and currently have (5) servers defined. If I click on 'Edit Servers' and select any of the existing servers, then make any modification (change name, modify ports, update password, etc.), a second entry is created in the list of servers. 

Even if I quit and restart the program, the additional entry (or entries if multiple entries were modified) still remain in the list. I need to either manually delete the entries via the GUI or by modifying the 'RconServers.json' file . See screen shots below. 

![1](https://user-images.githubusercontent.com/74274941/99692256-1c95cc80-2a58-11eb-9cfe-d0387383b92e.jpg)
![2](https://user-images.githubusercontent.com/74274941/99692259-1d2e6300-2a58-11eb-9d1e-8fabcae37a6a.jpg)
![3](https://user-images.githubusercontent.com/74274941/99692260-1d2e6300-2a58-11eb-81c0-1a35ea7a3582.jpg)

**Comment by cborrow** [comment]
Ok. That should be a quick fix to update. I will get that corrected and update this issue once it has been completed.

**Comment by cborrow** [comment]
Issue has been resolved and working with adding, editing, and removing servers has been updated.
