### ISSUE TITLE
View saved password?

### ISSUE THREAD

**Issue by otherguy1971** [cborrow/InsurgencySandstormRcon#5]
Suggested Feature: 

Currently, there appears to be no way to view a saved password once a server has been successfully configured. If I click on 'Edit Servers' and view an entry, the password field is blank. I assume this is intentional, rather than a bug. 

Perhaps consider changing the password field to a masked field that hides the password by default, but includes an option to allow the user to temporarily unmask and view the password? See screen shots below. 

![1](https://user-images.githubusercontent.com/74274941/99694333-5071f180-2a5a-11eb-879a-74a9ec167bc3.jpg)
![2](https://user-images.githubusercontent.com/74274941/99694334-5071f180-2a5a-11eb-9c7d-229cd926ca5f.jpg)

**Comment by cborrow** [comment]
This is definitely something I can add. I will add this while taking care of the previous issue of servers not being removed when deleted. Thanks.

**Comment by cborrow** [comment]
New ToggleablePasswordBox has been added to allow toggling visibility of password in ServerManagementDialog.
Changes can be found in newly release v 1.1
